fix: build settings
- 2.0.1 has a bug in the published copy which produces the following error:
  "Error: Cannot find module './pg_logicaldec.proto.json'"
  Caused by `tsc` not copying the proto.json file to the `./dist` dir during the build step.
  The easy way to fix this is to just make the file a `.ts` file instead of a `.json` file.

- Updated the `tsc` target to ES202, which correlates to the max target usable on Node 14.
- Removed the two peer dependencies as they are required prod dependencies already.